Feature ai assistant
PABixn/Muniffic pull request #36
Opened 2024-09-24 07:20 UTC by PABixn

2024-09-30 08:33 UTC, szymix200006 requested changes

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/EditorActions.cpp
> +			return std::to_string(entity.GetUUID());
Bring out the actions the functions.

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/EditorLayer.cpp
> +					break;
What  happened here?

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +		else
Move instructions to a textfile

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +		std::string line, language, msg = "";
Why only msg is set to an empty string

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +			memcpy(buffer, message.data(), message.size());
memory access vilolation possible

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +		ImGui::BeginChild("Messages", ImVec2(ImGui::GetWindowSize().x, availableHeight), false, ImGuiWindowFlags_HorizontalScrollbar);
Move message rendering to seperate function

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +	void AssistantPanel::OnImGuiRender()
Move big parts of a window to a separate functions

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.cpp
> +		}
Seperate logic from UI

2024-09-30 08:33 UTC, szymix200006 commented on Engine-Editor/src/Panels/ContentBrowserPanel.cpp
> +			Commands::ExecuteRawValueCommand(&padding, offset, std::string("ContentBrowserPanel-Padding"));*/
Why it's commented, should it be deleted?

2024-09-30 08:33 UTC, szymix200006 commented on Engine/premake5.lua
>  		"%{IncludeDir.ImGuizmo}",
Delete this file

2024-09-30 08:33 UTC, szymix200006 commented on Engine/src/Engine/Assistant/AssistantManager.h
> +		std::string lastVoiceMessage;
Move the variables with the biggest stride to the front

2024-09-30 09:07 UTC, szymix200006 requested changes

2024-09-30 09:07 UTC, szymix200006 commented on Engine/src/Engine/Assistant/AssistantManager.h
> +		PyObject* m_CheckAPI;
Set member variables to nullptr

2024-09-30 09:07 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.h
> +        ImGui::MarkdownConfig mdConfig;
Put the variables with biggest stride first

2024-09-30 09:07 UTC, szymix200006 commented on Engine-Editor/src/Panels/AddResourcePanel.h
> +		Ref<Texture2D> m_CustomIcon;
Set refs to nullptr

2024-09-30 09:07 UTC, szymix200006 commented on Engine-Editor/src/EditorActions.h
> +		static Entity* m_SelectedEntity;
Set to nullptr

2024-09-30 09:07 UTC, szymix200006 commented on Engine-Editor/src/Panels/AssistantPanel.h
> +        ImTextureID m_IconReadMessageAloud;
Set to nullptr

2024-09-30 16:55 UTC, miciex commented on Engine-Editor/src/EditorActions.h
> +		static std::string ExecuteComponentAction(const std::string& actionName, std::vector<std::string>& params);
vectors should be a const if the params arent set inside the function, which would be weird if it was the case

2024-10-01 07:58 UTC, miciex approved these changes

2024-10-01 08:30 UTC, szymix200006 approved these changes

2024-10-01 08:43 UTC, merged