Feature icon loader
PABixn/Muniffic pull request #45
Opened 2024-10-05 14:50 UTC by PABixn

Load all icons using IconLoader which ensures that everything is loaded correctly and provides easy access to it.

2024-10-08 15:17 UTC, miciex requested changes

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/IconLoader.cpp
> +		for(int i = 0; i < static_cast<int>(Icons::MAX); i++)
Why use an int here instead of size_t?

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/IconLoader.cpp
> +	Ref<Texture2D> IconLoader::m_DefaultIcon = nullptr;
Why is m_DefaultIcon seperated from m_Icons? I don't see a reason to treat it as something distinct

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/IconLoader.cpp
> +				return "resources/graphics/resource_not_found.png";
I would use a variable for the directory path here

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/IconLoader.cpp
> +				return "resources/graphics/resource_not_found.png";
I would use a variable for the directory path here

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/Panels/SceneHierarchyPanel.cpp
>  		m_ComponentIcons = std::vector<Ref<Texture2D>>();
Why this vector is here, now when the access to icons is easy it is no longer necessary. The icons should be accessed directly from IconLoader. Why waste memory

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/Panels/ResourcesPanels/AnimationEditorPanel.cpp
> +		m_MoveSelectedIcon = IconLoader::GetIcon(Icons::AnimationEditor_MoveIconSelected);
Similar thing as in hierarchy panel, no need to have member variables for Icons now.

2024-10-08 15:17 UTC, miciex commented on Engine-Editor/src/Panels/WelcomingPanel.cpp
> +		m_DeleteProjectIcon = IconLoader::GetIcon(Icons::WelcomePanel_DeleteProject);
No need to create member variables for Icons now.

2024-10-08 16:14 UTC, PABixn commented on Engine-Editor/src/IconLoader.cpp
> +		for(int i = 0; i < static_cast<int>(Icons::MAX); i++)
Because enums' elements are indexed by int.

2024-10-08 16:14 UTC, PABixn commented on Engine-Editor/src/IconLoader.cpp
> +	Ref<Texture2D> IconLoader::m_DefaultIcon = nullptr;
It's purpose is also to replace unloaded icons in order to prevent errors.

2024-10-08 16:22 UTC, PABixn commented on Engine-Editor/src/Panels/SceneHierarchyPanel.cpp
>  		m_ComponentIcons = std::vector<Ref<Texture2D>>();
Method of loading icons doesn't change anything here, the vector makes it easy to get icons in generic DrawComponent function.

2024-10-08 17:40 UTC, miciex commented on Engine-Editor/src/Panels/SceneHierarchyPanel.cpp
>  		m_ComponentIcons = std::vector<Ref<Texture2D>>();
You can do the same thing by changing the last argument from int to Icon enum and get the Icon from Icon loader directly, not necessary to add  extra complexity to loading icons.

2024-10-08 17:40 UTC, miciex commented on Engine-Editor/src/IconLoader.cpp
> +	Ref<Texture2D> IconLoader::m_DefaultIcon = nullptr;
Yea but it can serve that purpose inside the vector as well

2024-10-08 17:51 UTC, PABixn commented on Engine-Editor/src/IconLoader.cpp
> +	Ref<Texture2D> IconLoader::m_DefaultIcon = nullptr;
But it's used internally inside the iconloader so it is clearly different from the other ones and also there is no need to search the map.

2024-10-08 17:56 UTC, PABixn commented on Engine-Editor/src/Panels/SceneHierarchyPanel.cpp
>  		m_ComponentIcons = std::vector<Ref<Texture2D>>();
Actually yes

2024-10-10 12:23 UTC, miciex approved these changes

2024-10-10 12:25 UTC, merged